In [91]:
import pandas as pd
import torch
from torch.utils.data import TensorDataset, DataLoader
import torch.optim as optim
# Kiểm tra xem GPU có sẵn hay không, nếu không, sử dụng CPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Di chuyển mô hình và dữ liệu lên device
model.to(device)
data = data.to(device)
targets = targets.to(device)



In [92]:


# Load the data from the .pt file
label_train = torch.load("label_train.pt")
label_test = torch.load("label_test.pt")
data_train = torch.load("data_train.pt")
data_test = torch.load("data_test.pt")

# Now, you can work with the loaded data, which could be a PyTorch tensor or other Python objects.
print(label_train)
print(label_test)
print(data_train)
print(data_test)



tensor([[0, 0, 1],
        [1, 0, 0],
        [0, 1, 0],
        ...,
        [0, 1, 0],
        [1, 0, 0],
        [0, 0, 1]])
tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 1, 0],
        ...,
        [0, 1, 0],
        [0, 0, 1],
        [1, 0, 0]])
tensor([[[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [7.0742e-04, 2.2218e-04, 4.7107e-04,  ..., 3.2646e-04,
          1.0598e-03, 3.0864e-03],
         [3.8089e-03, 1.1963e-03, 2.5364e-03,  ..., 1.7577e-03,
          5.7062e-03, 1.6618e-02],
         ...,
         [1.9064e-07, 2.5339e-08, 3.6193e-08,  ..., 1.6972e-08,
          4.1270e-08, 4.9305e-08],
         [2.0723e-07, 4.5802e-08, 4.1823e-08,  ..., 5.1683e-08,
          1.0393e-07, 8.0843e-08],
         [5.4068e-07, 7.8605e-08, 4.5975e-08,  ..., 3.4725e-08,
          4.5185e-08, 5.0358e-08]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [2.3553e-04, 6.2131e-03, 6

In [4]:
print(label_train.shape)
print(label_test.shape)
print(data_train.shape)
print(data_test.shape)


torch.Size([6023, 3])
torch.Size([1506, 3])
torch.Size([6023, 128, 1500])
torch.Size([1506, 128, 1500])


In [78]:
# Prepare the data loaders
batch_size = 32
train_dataset = TensorDataset(data_train, label_train)
test_dataset = TensorDataset(data_test, label_test)

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size)

In [34]:
# # Define the LSTM model
# class SimpleLSTM(nn.Module):
#     def __init__(self, input_size, hidden_size, num_layers, num_classes):
#         super(SimpleLSTM, self).__init__()
#         self.hidden_size = hidden_size
#         self.num_layers = num_layers
#         self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)
#         self.fc = nn.Linear(hidden_size, num_classes)

#     def forward(self, x):
#         h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device)
#         c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device)

#         out, _ = self.lstm(x, (h0, c0))
#         out = self.fc(out[:, -1, :])
#         return out

In [35]:
# class CustomLSTM(nn.Module):
#     def __init__(self, input_size, hidden_size, num_layers, num_classes):
#         super(CustomLSTM, self).__init__()
#         self.hidden_size = hidden_size
#         self.num_layers = num_layers
#         self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)
#         self.fc1 = nn.Linear(hidden_size, 64)
#         self.relu1 = nn.ReLU()
#         self.dropout1 = nn.Dropout(0.4)
#         self.fc2 = nn.Linear(64, 32)
#         self.relu2 = nn.ReLU()
#         self.dropout2 = nn.Dropout(0.4)
#         self.fc3 = nn.Linear(32, num_classes)
#         self.softmax = nn.Softmax(dim=1)
    
#     def forward(self, x):
#         h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device)
#         c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device)

#         out, _ = self.lstm(x, (h0, c0))
#         out = self.fc1(out[:, -1, :])
#         out = self.relu1(out)
#         out = self.dropout1(out)
#         out = self.fc2(out)
#         out = self.relu2(out)
#         out = self.dropout2(out)
#         out = self.fc3(out)
#         out = self.softmax(out)
#         return out

In [87]:
# import torch.nn as nn

# class RNN_LSTM(nn.Module):
#     def __init__(self, input_size, hidden_size, num_layers, num_classes):
#         super(RNN_LSTM, self).__init__()
#         self.hidden_size = hidden_size
#         self.num_layers = num_layers
#         self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)
#         self.fc = nn.Linear(hidden_size, num_classes)  # Thay đổi số lớp đầu ra thành 3

#     def forward(self, x):
#         # Set initial hidden and cell states
#         h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device)
#         c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device)

#         # Forward propagate LSTM
#         out, _ = self.lstm(x, (h0, c0))

#         # Lấy đầu ra của bước cuối cùng
#         out = out[:, -1, :]

#         # Đưa qua lớp fully connected
#         out = self.fc(out)

#         return out

# # Initialize the model
# input_size = 1500  # Số chiều của đầu vào (cần điều chỉnh phù hợp với dữ liệu của bạn)
# hidden_size = 128
# num_layers = 2
# num_classes = 3  # Số lớp đầu ra là 3

# # Khởi tạo mô hình
# model = RNN_LSTM(input_size, hidden_size, num_layers, num_classes)


In [31]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

class LSTMModel(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, num_classes):
        super(LSTMModel, self).__init__()
        self.num_classes = num_classes
        #self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)
        self.linear1 = nn.Linear(128, 64)
        #self.linear2 = nn.Linear(64, 32)
        self.linear3 = nn.Linear(32, num_classes)
        self.softmax = nn.Softmax(dim=1)
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers=2, batch_first=True, dropout=0.2, bidirectional=False)
        self.dropout = nn.Dropout(0.5)

    def forward(self, x):
        h0 = torch.zeros(2, x.size(0), 128).to(x.device)  # Số lớp (num_layers) là 2
        c0 = torch.zeros(2, x.size(0), 128).to(x.device)

        out, _ = self.lstm(x, (h0, c0))
        out = out[:, -1, :]
        out = self.linear1(out)
        #out = self.linear2(out)
        out = self.linear3(out)
        out = self.softmax(out)
        return out





In [89]:
# Initialize the model
input_size = 1500  # Input features (adjust based on your data)
hidden_size = 128
num_layers = 2
num_classes = 3

#model = SimpleLSTM(input_size, hidden_size, num_layers, num_classes)
#model = CustomLSTM(input_size, hidden_size, num_layers, num_classes)
model = LSTMModel( input_size, hidden_size, num_layers, num_classes)
#model = RNN_LSTM( input_size, hidden_size, num_layers, num_classes)

# Define the loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [90]:
# Training loop
num_epochs = 10

for epoch in range(num_epochs):
    model.train()
    total_loss = 0
    for data, labels in train_loader:
        optimizer.zero_grad()
        outputs = model(data)
        loss = criterion(outputs, torch.argmax(labels, dim=1))
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {total_loss / len(train_loader)}")

# Evaluate the model
model.eval()
correct = 0
total = 0
with torch.no_grad():
    for data, labels in test_loader:
        outputs = model(data)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == torch.argmax(labels, dim=1)).sum().item()

print(f"Accuracy on the test set: {100 * correct / total}%")

Epoch [1/10], Loss: 1.0351791233612746
Epoch [2/10], Loss: 1.0081684520004919
Epoch [3/10], Loss: 0.9701611213583164
Epoch [4/10], Loss: 0.9383038834289268
Epoch [5/10], Loss: 0.9060143828392029
Epoch [6/10], Loss: 0.8510925413439514
Epoch [7/10], Loss: 0.7939566995101001
Epoch [8/10], Loss: 0.7435371074726973
Epoch [9/10], Loss: 0.6839905302360575
Epoch [10/10], Loss: 0.6484600866913165
Accuracy on the test set: 46.14873837981408%


In [38]:
num_epochs = 10

for epoch in range(num_epochs):
    model.train()
    total_loss = 0
    for data, labels in train_loader:
        optimizer.zero_grad()
        outputs = model(data)
        loss = criterion(outputs, torch.argmax(labels, dim=1))
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {total_loss / len(train_loader)}")
# Evaluate the model
model.eval()
correct = 0
total = 0
with torch.no_grad():
    for data, labels in test_loader:
        outputs = model(data)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == torch.argmax(labels, dim=1)).sum().item()

print(f"Accuracy on the test set: {100 * correct / total}%")


Epoch [1/10], Loss: 0.8994634375370368
Epoch [2/10], Loss: 0.8974518605640956
Epoch [3/10], Loss: 0.9019246716347952
Epoch [4/10], Loss: 0.9184131303792278
Epoch [5/10], Loss: 1.0015696779129997
Epoch [6/10], Loss: 0.915267271970315
Epoch [7/10], Loss: 0.8932461536750591
Epoch [8/10], Loss: 0.8914022057775467
Epoch [9/10], Loss: 0.8845253924213389
Epoch [10/10], Loss: 0.8764180903712278
Accuracy on the test set: 48.00796812749004%
